(()=>{"use strict";
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const Config={stage:{w:1600,h:780},daySeconds:90,cookMs:{pot:4200,grill:3600,oden:3000},prices:{pot:3500,grill:2200,oden:1800}};
const State={running:false,paused:false,time:90,sales:0,guests:0,drag:null,timer:null};
const Appliances=[...Array(3)].map((_,i)=>({id:`pot-${i}`,type:"pot",slot:i,state:"empty",item:null,timer:null})).concat([...Array(2)].map((_,i)=>({id:`grill-${i}`,type:"grill",slot:i,state:"empty",item:null,timer:null})),[{id:"oden-0",type:"oden",slot:0,state:"empty",item:null,timer:null}]);
const Art={potEmpty:"assets/foods/pot_empty.svg",potNoodle:"assets/foods/pot_noodle.svg",ramen:"assets/foods/ramen_egg.svg"};
function build(){const left=$("#cookLeft"),right=$("#cookRight");Appliances.forEach(a=>{const b=document.createElement("button");b.className=`appliance ${a.type}`;b.dataset.id=a.id;b.innerHTML=`<label>${a.type==="pot"?`냄비 ${a.slot+1}`:a.type==="grill"?`그릴 ${a.slot+1}`:"오뎅바"}</label><span class="art"></span><span class="bar"><i></i></span>`;(a.type==="pot"?left:right).append(b)});const row=$("#guestRow");for(let i=0;i<3;i++)row.insertAdjacentHTML("beforeend",`<article class="guest-slot" data-guest="${i}"><div class="bubble"><img src="assets/foods/ramen_egg.svg"></div><img src="assets/customers/office.png" alt="손님 ${i+1}"><div class="patience"><i></i></div></article>`);renderAll()}
function resize(){const v=window.visualViewport||window;const s=Math.min(v.width/Config.stage.w,v.height/Config.stage.h);$("#stage").style.transform=`scale(${s})`}addEventListener("resize",resize,{passive:true});visualViewport?.addEventListener("resize",resize,{passive:true});
function money(n){return n.toLocaleString("ko-KR")+"원"}function hud(){$("#time").textContent=`${String(Math.floor(State.time/60)).padStart(2,"0")}:${String(State.time%60).padStart(2,"0")}`;$("#timeFill").style.width=`${State.time/Config.daySeconds*100}%`;$("#sales").textContent=money(State.sales);$("#guestCount").textContent=State.guests+"명"}
function toast(t){const e=$("#toast");e.textContent=t;e.classList.add("show");clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.remove("show"),1300)}function say(t){const e=$("#boreumiText");e.textContent=t;e.classList.add("show");clearTimeout(say.t);say.t=setTimeout(()=>e.classList.remove("show"),1100)}
function render(a){const el=$(`[data-id="${a.id}"]`),art=el.querySelector(".art");el.classList.toggle("ready",a.state==="ready");el.classList.toggle("burnt",a.state==="burnt");if(a.type==="pot")art.innerHTML=`<img src="${a.state==="empty"?Art.potEmpty:a.state==="cooking"?Art.potNoodle:Art.ramen}">`;else art.textContent=a.state==="empty"?(a.type==="grill"?"♨":"🍢"):a.item==="dumpling"?"🥟🥟":"🍢🍢"}function renderAll(){Appliances.forEach(render);hud()}
function teleport(a,verb){const target=$(`[data-id="${a.id}"]`).getBoundingClientRect(),area=$(".characters").getBoundingClientRect(),scale=area.width/580,b=$("#boreumi");let x=(target.left+target.width/2-area.left)/scale-90;x=Math.max(-40,Math.min(340,x));b.style.left=x+"px";b.classList.remove("teleport","action");void b.offsetWidth;b.classList.add("teleport");setTimeout(()=>{b.classList.remove("teleport");b.classList.add("action")},110);setTimeout(()=>b.classList.remove("action"),650);say(verb)}
function accepts(a,item){if(a.type==="pot")return item==="noodle"||item==="egg";if(a.type==="grill")return item==="dumpling";return item==="oden"}
function dropItem(a,item){if(!State.running)return toast("먼저 영업을 시작해 주세요.");if(!accepts(a,item))return toast("이 재료는 다른 조리기구에 넣어주세요.");if(a.type==="pot"&&item==="egg"){if(a.state!=="cooking")return toast("면이 끓고 있는 냄비에 계란을 넣어주세요.");a.item="egg";teleport(a,"계란 톡!");render(a);return}if(a.state!=="empty")return toast("다른 빈 조리기구를 사용해 주세요.");a.state="cooking";a.item=item;teleport(a,a.type==="pot"?"조리 시작!":a.type==="grill"?"노릇하게 구울게!":"따끈하게 데울게!");render(a);const el=$(`[data-id="${a.id}"]`),bar=el.querySelector(".bar i"),ms=Config.cookMs[a.type];bar.style.transition=`width ${ms}ms linear`;requestAnimationFrame(()=>bar.style.width="100%");a.timer=setTimeout(()=>{a.state="ready";render(a);toast(`${a.type==="pot"?"라면":a.type==="grill"?"군만두":"오뎅"} 완성!`)},ms)}
function serve(a,g){if(a.state!=="ready")return toast("완성된 음식만 서빙할 수 있어요.");State.sales+=Config.prices[a.type];State.guests++;a.state="empty";a.item=null;const el=$(`[data-id="${a.id}"]`);el.querySelector(".bar i").style.transition="none";el.querySelector(".bar i").style.width="0";render(a);hud();teleport(a,"맛있게 드세요!");const slot=$(`[data-guest="${g}"]`);slot.animate([{transform:"translateY(0)"},{transform:"translateY(-8px)"},{transform:"translateY(0)"}],{duration:350});toast(`판매 +${money(Config.prices[a.type])}`)}
function start(){State.running=true;State.time=Config.daySeconds;State.sales=0;State.guests=0;$("#startButton").style.display="none";clearInterval(State.timer);State.timer=setInterval(()=>{if(State.paused)return;if(--State.time<=0){State.time=0;State.running=false;clearInterval(State.timer);$("#startButton").style.display="flex";$("#startButton strong").textContent="다시 시작";toast(`영업 종료 · 매출 ${money(State.sales)}`)}hud()},1000);hud();say("오늘도 따뜻한 한 그릇!");toast("영업 시작!")}
function payload(el){if(el.matches(".ingredient"))return{kind:"item",item:el.dataset.item,ghost:el.innerText.trim()};const a=Appliances.find(x=>x.id===el.dataset.id);if(a?.state==="ready")return{kind:"food",id:a.id,ghost:a.type==="pot"?"🍜":a.type==="grill"?"🥟":"🍢"};return null}
function point(e){return{x:e.clientX,y:e.clientY}}function target(e){const p=point(e);return document.elementFromPoint(p.x,p.y)}function ghostMove(e){const p=point(e),g=$("#dragGhost");g.style.left=p.x+"px";g.style.top=(p.y-(e.pointerType==="touch"?45:16))+"px"}function clearOver(){$$(".drop-over").forEach(x=>x.classList.remove("drop-over"))}
function down(e,el){if(e.pointerType==="mouse"&&e.button!==0)return;const p=payload(el);if(!p)return;e.preventDefault();el.setPointerCapture?.(e.pointerId);State.drag={pointer:e.pointerId,p};$("#dragGhost span").textContent=p.ghost;$("#dragGhost").classList.add("show");ghostMove(e)}function move(e){if(State.drag?.pointer!==e.pointerId)return;e.preventDefault();ghostMove(e);clearOver();const t=target(e);if(State.drag.p.kind==="item")t?.closest(".appliance")?.classList.add("drop-over");else t?.closest(".bubble")?.classList.add("drop-over")}
function up(e){if(State.drag?.pointer!==e.pointerId)return;e.preventDefault();const t=target(e),p=State.drag.p;if(p.kind==="item"){const el=t?.closest(".appliance");if(el)dropItem(Appliances.find(x=>x.id===el.dataset.id),p.item);else toast("재료를 조리기구에 놓아주세요.")}else{const b=t?.closest(".bubble");if(b)serve(Appliances.find(x=>x.id===p.id),+b.closest(".guest-slot").dataset.guest);else toast("완성 음식을 손님 말풍선에 놓아주세요.")}State.drag=null;$("#dragGhost").classList.remove("show");clearOver()}
function bind(el){el.addEventListener("pointerdown",e=>down(e,el));el.addEventListener("pointermove",move);el.addEventListener("pointerup",up);el.addEventListener("pointercancel",up)}
async function browserQA(){if(!new URLSearchParams(location.search).has("qa"))return;const result={};start();result.startButtonHidden=getComputedStyle($("#startButton")).display==="none";dropItem(Appliances[0],"noodle");dropItem(Appliances[3],"dumpling");dropItem(Appliances[5],"oden");result.immediateCooking=Appliances[0].state==="cooking"&&Appliances[3].state==="cooking"&&Appliances[5].state==="cooking";result.teleportTriggered=$("#boreumi").classList.contains("teleport")||$("#boreumi").classList.contains("action");await new Promise(r=>setTimeout(r,4400));result.independentTimers=Appliances[0].state==="ready"&&Appliances[3].state==="ready"&&Appliances[5].state==="ready";const stage=$("#stage").getBoundingClientRect(),dock=$(".dock").getBoundingClientRect(),guests=$("#guestRow").getBoundingClientRect(),left=$("#cookLeft").getBoundingClientRect(),right=$("#cookRight").getBoundingClientRect();result.landscape=stage.width>stage.height;result.noDockOverlap=dock.top>=Math.max(left.bottom,right.bottom)-2;result.guestsAboveCooking=guests.bottom<=Math.min(left.bottom,right.bottom);result.applianceCount=$$(".appliance").length===6;result.guestCount=$$(".guest-slot").length===3;const out=document.createElement("pre");out.id="qa-results";out.textContent=JSON.stringify(result);out.style.cssText="position:absolute;z-index:99999;left:0;top:0;background:white;color:black;font-size:12px";$("#stage").append(out);document.documentElement.dataset.qa=Object.values(result).every(Boolean)?"pass":"fail"}
build();$$('.ingredient,.appliance').forEach(bind);$("#startButton").onclick=start;$("#pauseButton").onclick=()=>{if(!State.running)return toast("영업 중에 사용할 수 있어요.");State.paused=true;$("#pauseOverlay").classList.remove("hidden")};$("#resumeButton").onclick=()=>{State.paused=false;$("#pauseOverlay").classList.add("hidden")};document.addEventListener("dragstart",e=>e.preventDefault());resize();browserQA();
})();
